language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

script:
 - bin/phpunit
 - bin/phpspec run --no-interaction
 - bin/behat --format progress

before_script:
 - composer selfupdate --quiet
 - composer install --no-interaction --prefer-source
