---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:

    - name: Link webroot to localhost:5000
      file: src=/vagrant/web dest=/var/www state=link

    - name: update existing packages
      apt: update_cache=yes

    - name: install packages
      apt: pkg={{item}} state=latest
      with_items:
      - vim
      - apache2
      - php5
      - mysql-server
      - php5-mysql
      - phpmyadmin
      - php5-xdebug

    - name: write php.ini
      template: src=templates/php.ini.j2 dest=/etc/php5/apache2/php.ini owner=root group=root mode=0644

    - name: Apache | Enable required modules
      action: command a2enmod rewrite

    - name: Apache | Configuration file for dev environment
      action: template src=templates/apache2-sites-available-dev.j2 dest=/etc/apache2/sites-available/dev

    - name: Apache | Disable default site
      action: command a2dissite default

    - name: Apache | Enable dev site
      action: command a2ensite dev

    - name: link phpmyadmin config to the correct path
      file: src=/etc/phpmyadmin/apache.conf dest=/etc/apache2/conf.d/phpmyadmin.conf state=link

      notify:
      - Apache | Restart Apache2

  handlers:
    - name: Apache | Restart Apache2
      service: name=apache2 state=restarted
